# Wrangler configuration for Cloudflare Pages
name = "utilixgames"
type = "webpack"
account_id = ""  # Your Cloudflare account ID will be inserted automatically
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2025-03-16"

[build]
command = ""  # No build command needed for static site
upload.format = "directory"
